name: Hostme Deployment

on: [push]

jobs:
  hostme_deployment_job:
    runs-on: ubuntu-latest
    name: Hostme.Space deployment

    steps:
      - uses: actions/checkout@v2
      - id: deployment
        uses: osscameroon/hostme.gh-action@v3
        with:
          api-token: '${{ secrets.HOSTME_API_TOKEN }}'
          commands: |
            echo "${{ github.event.repository.name }}" > h_name.out
